### ISSUE TITLE
can't seem to instal on Raspberry Pi

### ISSUE THREAD

**Issue by chasedWolf** [simonlast/node-persist#102]
Hi, i am new to the raspberry pi and so using these kind of programs.

For my Nuki lock i get the following error:
Error: EACCES: permission denied, mkdir '/run/s6/services/homebridge/.node-persist'

it seems i need to install Node-persist, is this correct?
i tried to do it on my Pi but it states that the command is not found: 

_pi@raspberrypi:~ $ npm i node-persist
-bash: npm: command not found_

what am i doing wrong?

**Comment by chasedWolf** [comment]
Hi Akhoury,

I have set up Homebridge through the installer, i am assuming Node should be installed, how can i check it?

**Comment by akhoury** [comment]
`node -v` 

you should see a version number. you think you may have installed `node` but not `npm`, I think that's only possible if you're compiling it yourself, most installers install `npm` with it.

i am closing this issue because it has nothing to do with this package.
