### ISSUE TITLE
Error thrown in `readFile` is not propertly handled in  `readDirectory`

### ISSUE THREAD

**Issue by tndev** [simonlast/node-persist#107]
If an error occures in `readFile` then this error is not correctly handled in `readDirectory`:

```js
  fs.readdir(dir, async (err, arr) => {
    if (err) {
      return reject(err);
    }
    let data = [];
    for (let i in arr) {
      let currentFile = arr[i];
      if (currentFile[0] !== '.') {
        data.push(await this.readFile(path.join(this.options.dir, currentFile)));
      }
    }
    resolve(data);
  });
```
As of that the following error could occure:

>     (node:13616) UnhandledPromiseRejectionWarning: Error: [node-persist][readFile] .node-persist/storage/37b51d194a7513e45b56f6524f2d51f2 does not look like a valid storage file!
>        at fs.readFile (node_modules/node-persist/src/local-storage.js:278:66)
>        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:525:3)
>     (node:13616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
>     (node:13616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

So the code should look something like this:

```js
  fs.readdir(dir, async (err, arr) => {
    if (err) {
      return reject(err);
    }
    let data = [];
    try {
      for (let i in arr) {
        let currentFile = arr[i];
        if (currentFile[0] !== '.') {
          data.push(await this.readFile(path.join(this.options.dir, currentFile)));
        }
      }
    } catch(err) {
       reject(err);
    }
    resolve(data);
  });
```

**Comment by akhoury** [comment]
pull requests are welcomed :)
