### ISSUE TITLE
await storage.init() returns an empty promise

### ISSUE THREAD

**Issue by alexryd** [simonlast/node-persist#120]
I noticed that [the global `init()` function](https://github.com/simonlast/node-persist/blob/master/src/node-persist.js#L23) is not declared as `async`, which means running `await storage.init()` returns a Promise that resolves without actually waiting for the `LocalStorage.init()` function to resolve.

The `callback` argument of `init()` doesn't work either since it is passed to `LocalStorage.init()` that rather expects some options instead of a callback.

So the way `init()` is implemented now, there is no way to actually wait for the initialisation to complete before accessing the storage. Or am I missing something?

**Comment by akhoury** [comment]
no you're right, good catch.

**Comment by akhoury** [comment]
https://github.com/simonlast/node-persist/commit/a7a9060f799e3a3bad17a041b6500b56ac926ce3

published `3.0.5`

**Comment by alexryd** [comment]
Great, thanks!
