### ISSUE TITLE
How to use asynchronous init()

### ISSUE THREAD

**Issue by nobody-65534** [simonlast/node-persist#122]
I need help on how to use the `async init()`

I am writing a module that looks like this: 
```js
// MyModule.js
const storage = require('node-persist');
await storage.init();

exports.foo = async () => {
  //do some staff
  await storage.set('foo', 'bar');
}
```
Since I cannot use `await` in the top level, I use IIAFEs suggested in #105  :
```js
// MyModule.js
const storage = require('node-persist');
(async () => {
  await storage.init();
})();

exports.foo = async () => {
  //do some staff
  await storage.set('foo', 'bar');
}
```
But the following code fails:
```js
// Main.js
const myModule = require('./myModule');

myModule.foo(); // fail because storage.set is undefined
```
The workaround I came up with:
```js
// MyModule.js
const storage = require('node-persist');

exports.foo = async () => {
  if(!this.storageInit) {
    await storage.init();
  }
  storage.set('foo', 'bar');
}
```
It works, but the first call of `foo` needs to wait for storage init. 
I also take a look at [ECMAScript proposal: Top-level await](https://github.com/tc39/proposal-top-level-await#workaround-export-a-promise-to-represent-initialization), but the promise workaround seems nasty to me. 
Wish to know if there's a better solution. Thanks.

**Comment by akhoury** [comment]
in your case, i would use `initSync` since you're using it at module load time, it's not really gonna affect your app's performance

**Comment by nobody-65534** [comment]
@akhoury Thank you! Since the `initSync` has been removed in the latest version, I'll stick to `2.1.0`.

**Comment by akhoury** [comment]
ah right! my bad! sorry, ironically i was the one who removed it - maybe that's a use case to bring back in till top level await ships in node

**Comment by jackHedaya** [comment]
I think initSync should be restored for this type of use case, people still using Node 10 or 12 will cannot use top level await
