### ISSUE TITLE
Error: EROFS: read-only file system, mkdir '/storage'

### ISSUE THREAD

**Issue by pociej** [simonlast/node-persist#125]
Im trying to use other livrary that sues node-persist https://github.com/nicolodavis/boardgame.io/tree/master/src 

Thats selfexplaining error, but problem is that even running as sudo gives same effect. I tried even create dir /storage manually, without success, still same error. Any idea how to solve this?

**Comment by akhoury** [comment]
depending on the system, you might not be allowed to create directories on the root directory
[ i.e. MAC OS Catalina ](https://discussions.apple.com/thread/250720711)

**Comment by sskanishk** [comment]
I'm getting the same error on google functions.
`Error: EROFS: read-only file system, unlink '.node-persist/storage/94c8aa2452bccd82ee129b46f7c4be79'`
Let me know if there is any solution.
Thanks

**Comment by akhoury** [comment]
wherever you're running this code, it's not letting you write to disk in a that directory, sorry i can't help you more than that.

**Comment by sskanishk** [comment]
> I'm getting this below error on google functions.
> `Error: EROFS: read-only file system, unlink '.node-persist/storage/94c8aa2452bccd82ee129b46f7c4be79'`
> Let me know if there is any solution.
> Thanks

Solution:
On Cloud i.e. cloud function , `write file` is only works on `/tmp` or `os.tmpdir()`
Thanks
