### ISSUE TITLE
[Enhancement] Storage folder inside other storage folder is a bad idea

### ISSUE THREAD

**Issue by Timmiej93** [simonlast/node-persist#132]
I spent way too much time on this issue today, so this is for everybody doing the same dumb thing I did:

```lang-js
const nodePersist = require("node-persist");
const storage1 = nodePersist.create({ dir: ".node-persist/storage1" });
const storage1b = nodePersist.create({ dir: ".node-persist/storage1/storage1b" });
```

This will ***not*** work.

This will give you an extremely undescriptive error : `EISDIR: illegal operation on a directory, read`. I understand that this may not be the intended use, and it's too much effort to make this possible, but a clearer error message, or a more detailed description in the readme would be very helpful, because I read `..., just avoid using the same dir for the storage location.` as `don't use the same directory multiple times`.

**Comment by towfiqi** [comment]
So how did you fix this?

**Comment by akhoury** [comment]
don't use the same folder or parent folder for 2 different instances of Storage.

**Comment by towfiqi** [comment]
@akhoury I am using 3 separate storages in 3 different cache directory and still getting the illegal operation error every few minutes:

```
const productStorage = storage.create({ dir: 'cache_products',ttl: true, forgiveParseErrors: true }); productStorage.init();
const reviewStorage = storage.create({ dir: 'cache_reviews',ttl: true, forgiveParseErrors: true }); reviewStorage.init();
const suppliersStorage = storage.create({ dir: 'cache_suppliers',ttl: true, forgiveParseErrors: true }); suppliersStorage.init();
```

Any idea what the issue could be?

**Comment by akhoury** [comment]
hmm.. `init()` is async, can you wait for each to finish at first? (or use )

```javascript
// use this if you don't have top-level await yet in your node version: https://v8.dev/features/top-level-await
(async () => {


  const productStorage = storage.create({ dir: 'cache_products',ttl: true, forgiveParseErrors: true }); 
  await productStorage.init();
  
  const reviewStorage = storage.create({ dir: 'cache_reviews',ttl: true, forgiveParseErrors: true }); 
  await reviewStorage.init(); 
  
  const suppliersStorage = storage.create({ dir: 'cache_suppliers',ttl: true, forgiveParseErrors: true }); 
  await suppliersStorage.init();


  // ... rest of your code here
})();

```

**Comment by towfiqi** [comment]
Thank you. That seem to have fixed the issue :)
