### ISSUE TITLE
Just a Question: Version 3 "All the *Sync functions were removed, every operation is now asynchronous"

### ISSUE THREAD

**Issue by Bonfims** [simonlast/node-persist#136]
Hey,

On readme says "All the *Sync functions were removed, every operation is now asynchronous" and all the examples uses "await" and "async" functions, i missing something?

How should i use now? storage.init(..).then( ()=> { ... })

Sorry to make this on a "issue".

**Comment by akhoury** [comment]
every operation now returns a "[Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)", which means you can use either ways, you can either `await promise` or `promise.then()`,

this could still get messy though.

```javascript
storage.init(..).then(() => { 
    storage.setItem('foo', 1).then(() => {
        storage.getItem('foo').then((v) => {
            console.log(v)
        })
    })
})
```

I prefer async/await 

```javascript
await storage.init(....)
await storage.setItem('foo', 1)
const v = await storage.getItem('foo')
console.log(v)
```

you can even use both, hehe, but i wouldn't, generally speaking.
```javascript
await storage.init(....).then(() => {})
```

keep in mind, I am not handling exceptions in those examples.
