### ISSUE TITLE
Getting this error intermittently: 'Error: EMFILE: too many open files'

### ISSUE THREAD

**Issue by mdodge-ecgrow** [simonlast/node-persist#142]
Lately we have been getting this error intermittently when trying to run this line: `shiftNumber = await storage.getItem('shift');`.  A couple questions I have.

1. Would your latest update you pushed out yesterday help with that at all? (3.1.2)
2. Should I be running this call every single time I get or set an item? `await storage.init({ dir: nodePersistDir });`  Because that is the way I am currently doing it.  I got to thinking now and maybe I should only do that when the Node server starts up?
3. Would this option help my issue at all?  `expiredInterval: 2 * 60 * 1000, // every 2 minutes the process will clean-up the expired cache`

Thanks for all your work on this library!  It is very useful.

**Comment by akhoury** [comment]
1) i don't think it's related
2) **99.99% sure that is your issue, `storage.init()` should be called once per node process, so yea, only when the node server starts ip**
3) you should use clean up expired files, that would help for sure.

**Comment by mdodge-ecgrow** [comment]
Thank you so much for getting back to me!  I will make that change in the code.  Just a thought, maybe you could add a line into the github Readme that that `storage.init()` call should only be made once per Node process, not everytime you read or write data.  I know that is probably obvious to a lot of programmers, but it was not initially obvious to me. :)

Thank you again so much!
