### ISSUE TITLE
Attempting to throw non-existent error

### ISSUE THREAD

**Issue by joepie91** [simonlast/node-persist#32]
I just ran into this error:

```
/home/sven/projects/pdfy/node_modules/node-persist/node-persist.js:538
            callback(err, result);
                     ^
  ReferenceError: err is not defined
  
  - node-persist.js:538 
    [pdfy]/[node-persist]/node-persist.js:538:22
```

The responsible bit of code is [here](https://github.com/simonlast/node-persist/blob/master/node-persist.js#L538) - it doesn't appear to set `err` anywhere, thus it has nothing to throw.

**Comment by akhoury** [comment]
oops, my bad.
your workaround is the right solution, can you submit a PR ?

**Comment by joepie91** [comment]
PR is submitted.
