### ISSUE TITLE
Pull requests

### ISSUE THREAD

**Issue by joepie91** [simonlast/node-persist#34]
A brief side-question: what kind of PRs are you interested in? I've written my own wrapper with some extra methods to provide some Redis-like functionality, but it's not clear to me whether this module is meant to be a minimal core, or whether that kind of functionality would be appreciated as a PR.

For reference, the following are the things I've implemented so far:
- increment(key, amount = 1)
- decrement(key, amount = 1)
- addListItem(key, item)
- removeListItem(key, item)
- removeListItemByFilter(key, filterFunc)
- setProperty(key, property, value)
- removeProperty(key, property)

As my code is in Coffeescript and this project is not, it'd take some amount of effort and time to port it to 'vanilla' Javascript, so I figured I'd inquire about the demand for it first.

**Comment by simonlast** [comment]
Sorry for the delay. I am open to merging in functionality that people find useful!

**Comment by akhoury** [comment]
I personally like these helpers, just have few questions if you don't mind answering.

* do these __mutators__ return the promise appropriately?
* do you have a synchronous version of each __mutator__? i.e. `incrementSync`

* They all make an assumption about the type of the "value": 
    * `increment/decrement`, assumes that the type "of the object referenced by" key, is a__Number__, what if it's not?
    * `addListItem/removeListItem/removeListItemByFilter`, assumes that the type "of the object referenced by" key, is an __Array__, what if it's not?
    * `setProperty/removeProperty` assumes that the type "of the object referenced by" key, is a __Hash__, what if it's not?

**Comment by akhoury** [comment]
stale issue, closing, reopen if needed
