### ISSUE TITLE
export a storage factory

### ISSUE THREAD

**Issue by calebthebrewer** [simonlast/node-persist#39]
I know that this library is meant to simulate `localStorage`, but one feature that would make it more flexible is the ability to create many of them, (which can be initialized using different options).

**Comment by akhoury** [comment]
+1

But initializing 2 instances with the same target storage directory might get ugly, but you already know that.

**Comment by simonlast** [comment]
Maybe we could add a `storage.createStorage(options)` which returns a `storage`. Then we could have the best of both worlds?

**Comment by calebthebrewer** [comment]
Exporting a constructor seems like a good solution, but I can't see a path to that without moving all of the current exports onto some prototype. @simonlast is there another way to get there with a smaller diff?

**Comment by akhoury** [comment]
so.. yea, it wasn't a small diff. It's ok - i think it had to be done at some point.

@calebthebrewer feel like helping with the testing? so far all looks good, but I could use another set of eyes on it.

fork here: https://github.com/akhoury/node-persist
also, @simonlast read this [note](https://github.com/akhoury/node-persist#createoptions---synchronous-static-method)
