### ISSUE TITLE
License Relese

### ISSUE THREAD

**Issue by ShimiT** [simonlast/node-persist#42]
Hi,

Do you plan to release it? MIT...
If yes when ?

Regards,
Shimi

**Comment by simonlast** [comment]
It says BSD in the package.json so I suppose, that's what it is.

**Comment by akhoury** [comment]
actually, @simonlast npm complains about the license, 

```
npm WARN package.json node-persist@0.0.8 license should be a valid SPDX license expression
```

So i think you need to pick which BSD license

https://spdx.org/licenses/

**Comment by simonlast** [comment]
Oh man there are so many... Simplified maybe?

**Comment by akhoury** [comment]
i never bothered thinking about this too much, I usually just use either [MIT](https://spdx.org/licenses/MIT.html) or [WTFPL](https://spdx.org/licenses/WTFPL.html) - if Simplified BSD is what you want, I'll make the change, it would then be `BSD-2-Clause`

**Comment by simonlast** [comment]
MIT would be fine. That's what I usually use.

**Comment by akhoury** [comment]
https://github.com/simonlast/node-persist/commit/b996d8fc1c70a313330a7e4a2651d321663aa81c
