### ISSUE TITLE
Can I persist functions or just non prototyped data

### ISSUE THREAD

**Issue by mapaiva** [simonlast/node-persist#44]
I'm searching for a simple way to persist a array between a master and child process. I want to know if with `node-persist` I can do that trick, withouy using `eval` or ` new Function(...)` alternativies.

Thanks

**Comment by akhoury** [comment]
node-persist saves JSON strings to disk. That won't work for you, unless like you mentioned, you store the sources and you re-eval on read.

I suggest you use [messaging](https://nodejs.org/api/child_process.html#child_process_child_send_message_sendhandle_callback) between a master and a child, you can pass along memory references, such as functions.

**Comment by mapaiva** [comment]
I'm using that strategy right now, but send not allow pass functions too. :disappointed: . I'll try a child/parent communication with some work arounds. Thank you very much @akhoury
