### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by akhoury** [simonlast/node-persist#47]
Im thinking mocha

**Comment by simonlast** [comment]
Mocha sounds good.

**Comment by akhoury** [comment]
added about 21 tests, still todo TTL and Interval tests.
https://github.com/simonlast/node-persist#tests

**Comment by akhoury** [comment]
added TTL and interval tests, 
https://github.com/simonlast/node-persist/commit/58ef43c77018dab7e647dc0e764f4a9f1746a46a
