### ISSUE TITLE
Create tags on github

### ISSUE THREAD

**Issue by moroine** [simonlast/node-persist#54]
Hi, 

I found your repository and it seems to do a great job with a nice simple API. I saw in the package.json that your current version is 0.0.11. I think it would be great to add gihub tag according to your releases in order to let people use an older version and do upgrade willingly and not each time we run `npm install`

Thank You,

**Comment by akhoury** [comment]
@moroine we should do that, you're right, but `npm install` should respect the version that you specify in your `package.json`, it has nothing to do with the github tags.

how does __your application__'s `package.json` look like?
```
  "dependencies": {
    "node-persist": "0.0.11", // npm will respect that version
  },
```

see http://semver.npmjs.com/ and try it out. 
For patch releases, we will not break backward compatibility, so if you specify something like `0.0.x` you are guaranteed only necessary bug fixes.
