### ISSUE TITLE
more than one storage for node application

### ISSUE THREAD

**Issue by lmacardoso** [simonlast/node-persist#55]
I have some dificulties on have more than one storage for node application. If I have two storages can't access to keys on second storage.

**Comment by akhoury** [comment]
can you write an example?

**Comment by lmacardoso** [comment]
var cache1 = require('node-persist');
var cache2 = require('node-persist');
var appRoot = require('app-root-path');

cache1.initSync({
    dir: appRoot + '/cache1',
    stringify: JSON.stringify,
    parse: JSON.parse,
    encoding: 'utf8',
    logging: false,  // can also be custom logging function
    continuous: true,
    interval: false,
    ttl: false, // ttl* [NEW], can be true for 24h default or a number in MILLISECONDS
});

cache2.initSync({
    dir: appRoot + '/cache2',
    stringify: JSON.stringify,
    parse: JSON.parse,
    encoding: 'utf8',
    logging: false,  // can also be custom logging function
    continuous: true,
    interval: false,
    ttl: false, // ttl* [NEW], can be true for 24h default or a number in MILLISECONDS
});

var st_cache2 = cache2.getItemSync('1');
console.log('st_cache2 -> ' + JSON.stringify(st_cache2));

var st_cache1 = cache1.getItemSync('1');
console.log('st_cache1 -> ' + JSON.stringify(st_cache1));

cache1.setItemSync('1', {a:'b'});
cache2.setItemSync('1', {a:'c'});

//cache1.removeItemSync('1');

console.log('end');

**Comment by akhoury** [comment]
if you need to use it for 1 instance, you need to create an instance for each, you can't use the default one.

```javascript
var nodePersist = require('node-persist');
var appRoot = require('app-root-path');

var cache1 = nodePersist.create({
    dir: appRoot + '/cache1'  // removed your other options since they are the defaults
  });
cache1.initSync(); // no need to pass the options again here if you use create()

var cache2 = nodePersist.create({
    dir: appRoot + '/cache2'  // removed your other options since they are the defaults
});
cache2.initSync(); // no need to pass the options again here if you use create()

/* 
    also modified the order here, 
    so now I set 2 items, 
     then read them 
     then delete them, 
     then read them again to make sure they were deleted.
*/

cache1.setItemSync('1', {a:'b'});
cache2.setItemSync('1', {a:'c'});

console.log('st_cache1 ->', cache1.getItemSync('1'));
console.log('st_cache2 ->', cache2.getItemSync('1'));

cache1.removeItemSync('1');
cache2.removeItemSync('1');

console.log('\nAfter deletion, should be undefined');

console.log('st_cache1 ->', cache1.getItemSync('1'));
console.log('st_cache2 ->', cache2.getItemSync('1'));

console.log('\nend');
```

**Comment by akhoury** [comment]
I did update my comment a few times there, so ignore the first email you get, read my previous comment on the thread.
