### ISSUE TITLE
async getItem promise

### ISSUE THREAD

**Issue by Jamtis** [simonlast/node-persist#56]
I would like to know why it's impossible to return a promise for `getItem`.
```
function getItemAsync(key) {
  return new Promise((resolve, reject) => {
    storage.getItem(key, (value, error) => {
      if (error) reject(error);
      else resolve(value);
    });
  });
}
```
Seems to do the job for me.

**Comment by akhoury** [comment]
it's not impossible, it would break backward compatibility.

**Comment by Jamtis** [comment]
If that's the only reason not to implemt it. I'd suggest to add it to the next major release with a warning.

**Comment by akhoury** [comment]
we will

**Comment by akhoury** [comment]
https://github.com/simonlast/node-persist/commit/5c09328ae20cc3493cfaf075ac6c083a4dab2362
