### ISSUE TITLE
valuesWithKeyMatch as documented

### ISSUE THREAD

**Issue by jtakalai** [simonlast/node-persist#58]
This is from the documentation:
```
storage.setItem("batman", {name: "Bruce Wayne"});
console.log(storage.valuesWithKeyMatch('man')); //output: [{name: "Bruce Wayne"}
```

but local-storage.js implementation has
`return match.indexOf(key) !== -1;`
where match is "man" and key is "batman". It will not match because there is no "batman" in "man" but the other way around. I'm not sure if this is intentional and I'm just holding it wrong.

At any rate, I could fix it by wrapping my search string into RegExp.

**Comment by akhoury** [comment]
Fixed! thanks for catching that, and published [node-persist@0.0.12](https://www.npmjs.com/package/node-persist)
