### ISSUE TITLE
Relative paths are relative to wrong directory

### ISSUE THREAD

**Issue by zatch** [simonlast/node-persist#59]
When using the standard storage.initSync(), files are saved to ./persist, as expected. When using the factory method (sample code below), files are saved to ./node_modules/node-persist/src/storage.

Sample code:
```
var storage = require('node-persist');
var usersStorage = storage.create({dir: 'users'});
usersStorage.initSync();

var batman = {
    first: 'Bruce',
    last: 'Wayne',
    alias: 'Batman'
};

usersStorage.setItem('batman',batman);
```

In this example, the file 'batman' is saved to ./node_modules/node-persist/src/storage/users. The desired outcome is to have the file saved to ./persist/users.

Is this a bug or am I doing something wrong in my code?

Thanks in advance!

**Comment by akhoury** [comment]
hmm... I see your point, and I honestly like it a little more than the current behavior, but it has been like that since the beginning and changes would break backward compatibility. I will make sure to fix it once we decide to do publish a major version.

For the meantime, try using full paths, 
```
var usersStorage = storage.create({dir: __dirname + '/users'});
```

**Comment by zatch** [comment]
Thanks, this was the perfect fix for my problem!

**Comment by evilandfox** [comment]
well, I have many troubles with this package before saw this issue. Thanks. It is bad that this wasn't remark in readme

**Comment by evilandfox** [comment]
anyway, have to stop using this tool having many troubles. it's not "install and run without problems".
The trouble is
`storage.initSync({dir: path.join(__dirname, 'answers')});
storage.setItemSync(str, val);
console.log(storage.length(), storage.values());
`
throws error
`Error: ENOENT: no such file or directory, open 'D:\script\lib\answers\                007-01,  12-01-007-02,`
Windows 7 prof x64
