### ISSUE TITLE
Special character in windows

### ISSUE THREAD

**Issue by raghu12133** [simonlast/node-persist#60]
Keys with special characters (\ / * ? " <> | )  fails to create the file entry in windows since its not allowed.

**Comment by akhoury** [comment]
kind of a dup of https://github.com/simonlast/node-persist/issues/51

this issue is on our radar, but it introduces a breaking change, unless I make it optional to hash the keys.

**Comment by raghu12133** [comment]
ok. Got it

**Comment by akhoury** [comment]
fyi- `node-persist@2.0.0` is published, using md5 hash for filenames now.
https://github.com/simonlast/node-persist#200-change-logs
https://github.com/simonlast/node-persist/commit/0eaf17a307fb0fa7e6e74a00ab71fc6fc71efa37
