### ISSUE TITLE
getItem returns empty string

### ISSUE THREAD

**Issue by marcemira** [simonlast/node-persist#64]
I have a file `.node-persist/storage/023a024fab1608b372fdef427ec098ea` with regular json data on it. The problem is that the file does exist and all, but node-persist throws the following on the getItem:
```
/home/me/my-project/node_modules/node-persist/src/local-storage.js:578
            self.data[input.key] = input;
                           ^

TypeError: Cannot read property 'key' of undefined
    at /home/me/my-project/node_modules/node-persist/src/local-storage.js:578:28
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)

Process finished with exit code 1
```
 and I proved that is readable by executing this on node:
```
fs.readFile('.node-persist/storage/023a024fab1608b372fdef427ec098ea', 'utf8', (e, t) => { console.log(JSON.parse(t));});
```
returns a valid json printed on the terminal.

Doing some debugging on local-storage.js. Found out that the `text` param on the callback is an empty string(`""`), and that's why it can't be parsed and used as expected.

Any clues? Thanks

**Comment by akhoury** [comment]
hmm .. that's a little weird. Do you think the `dir`, you got in `this.options.dir` is correct? or even the `this.options.encoding`

also, are you on the most recent version? and what your node version?

empty string and no error huh? that's a new one.

**Comment by marcemira** [comment]
indeed, checked dir, encoding is utf8. I'm also using master(2.0.2), running on node 6.5. Any ideas? :/ sorry for the delay

**Comment by marcemira** [comment]
Using jsonLint package, i figured out that some files would randomly save with an extra `"}}` at the end of the file, causing the parse not to work. Also found empty files as well... weird :/, but managed to solve my issue like this

**Comment by telunc** [comment]
I'm also getting `Cannot read property 'key' of undefined`. It's indeed very weird.

**Comment by akhoury** [comment]
@telunc can you turn on logging? 
```
storage.init({
        // ... 
	logging: true,
       //...
```
also, can you paste the whole error with the stack trace?
