### ISSUE TITLE
Program hangs using v2.0.4 and greater

### ISSUE THREAD

**Issue by andrewjmead** [simonlast/node-persist#68]
I tried running this simple example using both 2.0.3 and 2.0.4. Here's the script:

```javascript
var storage = require('node-persist');

storage.initSync();
storage.setItemSync('test', 'test')
```

Using 2.0.3, the script runs and I'm returned to the command prompt. This is expected.

Using 2.0.4, the program hangs and I have to use ctrl+c to end the process. Any idea why this is happening?

**Comment by akhoury** [comment]
ok, the reason why this happens is because there is a task running on an interval now to delete the expired keys which was introduced in `v2.0.4` - you can always close the process, this way
```javascript
var storage = require('node-persist');
storage.initSync();
storage.setItemSync('test', 'test')
process.exit(0);
```

OR if you want, in `v2.0.7` I just added support disable the background task

```
var storage = require('node-persist');
storage.initSync({
    expiredInterval: false
});
storage.setItemSync('test', 'test');
```
