### ISSUE TITLE
Deleting Storage Folder throws error on first start

### ISSUE THREAD

**Issue by Jan-Ka** [simonlast/node-persist#69]
Hello,

Not sure if this is a Problem of node-persist or Node but when I delete the Storage Folder a ENOENT error is thrown on first start.

`
Error: ENOENT: no such file or directory, open 'd:\path\to\project\projectname\server\storage\hash'
`

It fixes itself if you just restart the app but It cripples my deployment script. Is there a Cache File somewhere I need to delete? 

Thanks for the Help

**Comment by akhoury** [comment]
are you deleting while your application is running? 

or are you killing the app, deleting the storage folder, then restarting to see the ENOENT error?

**Comment by akhoury** [comment]
Also, can you provide a full stack trace please, I just need lines numbers, feel free to obfuscate the full filepaths

**Comment by Jan-Ka** [comment]
Thanks for the fast response!

I'm terminating node, removing the storage files and folder and then starting the application again.

Here's what I got:

```
// console output
d:\path\to\project\projectname\node_modules\node-persist\src\local-storage.js:36
        if (err) throw err;
                 ^
Error: ENOENT: no such file or directory, open 'd:\path\to\project\projectname\server\storage\6a99c575ab87f8c7d1ed1e52e7e349ce'
    at Error (native)

//npm-debug.log
14 verbose stack Error: projectname@1.0.0 dev: `npm run startInternal`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid projectname@1.0.0
```

I hope that's everything? Can't seem to convince node to provide any more information.

Tried debugging but can't see anything out of the ordinary
```
//callstack from debugging, backtracing from thrown error
noop					local-storage.js	36
(anonymous function)	local-storage.js	447
(anonymous function)	fs.js				1305
(anonymous function)	fs.js				123
```

I can see the folder was created successfully on the FS.

**Comment by akhoury** [comment]
can you provide the following:
• `node --version`
• the version of the `node-persist` package you are using
• show me the block of the code that you are using to `init/initSync` the storage instance.

Also, are you using some sort a master Node process to spawn and handle other Node processes? like a cluster or something? can you share what `npm run startInternal` is doing? I suspect you have a multiple processes and one of them is not getting killed.

This is really weird, the test cases [always delete the storage dirs](https://github.com/simonlast/node-persist/blob/master/tests/index.js#L376-L378) with no issues, maybe there is a case we didn't cover.

I'd be happy to help but I need a little more. Is your project open source?

**Comment by Jan-Ka** [comment]
No, it's not open source - but I will try to provide all information:

```
d:\path\to\project\projectname>node --version
v6.4.0

d:\path\to\project\projectname>npm -v node-persist
3.10.3
```
And the npm scripts
```
"scripts": {
    "start": "npm run build && npm run startInternal",
    "build": "webpack -p --config webpack.production.config.js",
    "startInternal": "node -r dotenv-safe/config server"
  }

//during development, app is started with 'npm run startInternal'
```
As well as the storage init:
```
// server\index.js - entry point
const storage = require("node-persist");

storage.init({
    dir: "server/storage"
});
```
Nothing is interacting with storage in any way.

I try to recreate the problem in a different project that I can share.

**Comment by Jan-Ka** [comment]
Here you go: https://github.com/Jan-Ka/verbose-succotash

**Comment by akhoury** [comment]
awesome! thanks for this! i will take a look tonight

**Comment by akhoury** [comment]
ok, so here's what's happening, you're trying to `setItem()` before the storage has finished initializing, and creating the the storage directory, that's why it only does it the first time, the second time the directory is already created.

When you use [`storage.init()`](https://github.com/Jan-Ka/verbose-succotash/blob/ba31f232469e2c8bee946dc70a3bc8aa075c1004/server/index.js#L3-L5), this is not synchronous, you need to wait for it to be ready before you can use it.

you can solve this in 2 ways, either, 

Wait for it to be done, before using it
```javascript
storage.init().then(()=> {
    // start your app here.
});
```

## OR 

Use the synchronous version of `init`  - this is OK if you are doing it at app-load time, it will not really impact performance

```javascript
storage.initSync();
// start your app here.
```

**Comment by Jan-Ka** [comment]
Thank you for the quick fix - i just tested it and it works fine.

Somehow I didn't think of testing the Problem without setting a variable :)

Code for reference:
```javascript
const storage = require("node-persist");

let storageInit = storage.init({
    dir: "server/storage"
});

const argvs = process.argv.slice(2);

if (argvs[0] === "setup") {
    console.log("INIT", "SETITEM", "WAIT 5s", "EXIT");

// here be changes
    storageInit.then(() => {
        storage.setItem("demo",
            [
                {
                    "demo": "data"
                }
            ]
        ).then(
            function () {
                console.log("SETITEM SUCCESSFULL");
            },
            function (reason) {
                console.log("SETITEM ERROR", reason);
            });
    });
} else {
    console.log("INIT", "WAIT 5s", "EXIT");
}

setTimeout(() => {
    process.exit();
}, 5000);
```
