### ISSUE TITLE
[Question] nested values?

### ISSUE THREAD

**Issue by skillzzjesse** [simonlast/node-persist#70]
Hey, quick question..

**Does your module allow for nested values?**
For example I want to store something like this:
```js
{
   key1: {
      child1: itsObject,
      child2: itsObject
      // Etc...
   },
   key2: {
      child1: itsObject,
      child2: itsObject
      // Etc...
   },
   // Etc....
}
```

Could I go

```js
storage.setItem([key1][child1], itsObject);
```
Or would that return the following?
```js
{
"[key1][child1]": itsObject
}
```

**Comment by akhoury** [comment]
unfortunately it doesn't. Every key gets hashed into a unique filename.

**Comment by skillzzjesse** [comment]
Ooh, alright! I guess I'll just have to create different objects for every child and make the naming a combo of the parent and child. That'll do. Less convenient tho. But It'll do! 

```js
Parent1child1: itsObj
// etc... 
```
