### ISSUE TITLE
Weird parsing errors? [google drive sucks]

### ISSUE THREAD

**Issue by jessevdp** [simonlast/node-persist#72]
Alright so, I use two main system to write all my code on. Yesterday, as you may remember I was working with your module as described in #71. Then today I came back to continue working on it and something strange started happening. 

![image](https://cloud.githubusercontent.com/assets/15139826/20767638/549c246a-b73b-11e6-9813-e922f1ecb2ae.png)

So I started commenting out the code that I thought might cause this weird error up until the point where I had only the following left...

```js
 var storage = require('node-persist');

 /* Init our storage */
 storage.init({
   dir: './cachefolder'
 });
```

I then uncommented everything and saw that everything inside the file actually ran. This means that data was saved to the cache, it was then read from the cache and printed to the console. The data was retrieved from the cache once again and some stuff was calculated with the data upon which something else was printed. 

Only after all this was done the error printed.

**Also note that**  removing the part where I init the storage makes sure this error isn't thrown, but this is to be expected since the error occurs in one of the files inside of the node-persist storage module.

**Comment by skillzzjesse** [comment]
I'm on node **v6.9.1** if that means anything. Running on bash for windows, their beta version I believe. (yes microsoft is embracing bash into their CLI)

**Comment by akhoury** [comment]
can you turn on logging, with 

```javascript
storage.init({
   dir: './cachefolder',
   logging: true // <-- add this
})
```

Also, does it make a difference if you use `initSync` instead of `init`, so 

```javascript
storage.initSync({ // <-- try initSync
   dir: './cachefolder',
   logging: true
})
```

**Comment by skillzzjesse** [comment]
I'm confused as to why it didn't error on my Mac... 

And what would this logging achieve? 
I'll try the sync version tomorrow... But for my purposes I do need async soo

**Comment by akhoury** [comment]
> And what would this logging achieve?

logging would print the parsing error

> I'll try the sync version tomorrow... But for my purposes I do need async soo

this is just the init step getting done synchronously, everything else would still be async if you're using the async version of the functions

**Comment by skillzzjesse** [comment]
Alright, so it's cool that it logs the error. However... I'm more curious about why it errors. I'm not doing anything in the file except for initializing the storage... Yet it  errors?

**Comment by skillzzjesse** [comment]
Oeps, I just re read your reply. 

I'll turn logging on when I get home and see what the actual error is. I'll also try the sync version to see if it makes  a difference. 

I'll let you know when I get time to test.

**Comment by skillzzjesse** [comment]
Alright, so I've turned logging on as you described earlier. Which get's  me the following result:
![image](https://cloud.githubusercontent.com/assets/15139826/20797412/e0af83bc-b7da-11e6-9175-919253ddee5e.png)

Then I also made sure to change the init function to initSync, which gave me this:
![image](https://cloud.githubusercontent.com/assets/15139826/20797521/5bda99be-b7db-11e6-9ec2-88293265873c.png)

## conclusion
It still error's and the error is empty even.

**Comment by skillzzjesse** [comment]
### update
So I'm back on my mac now, previously it didn't error, however it does now. It's weird, as the issue's title suggests. 

Are you able to recreate the error? 
I'm on **v2.0.7** of node-persist

<img width="698" alt="screen shot 2016-12-04 at 17 21 24" src="https://cloud.githubusercontent.com/assets/15139826/20867488/230d758a-ba46-11e6-9e6e-720390d0cb54.png">

**Comment by akhoury** [comment]
can you put a logging statement on [line:625](https://github.com/simonlast/node-persist/blob/master/src/local-storage.js#L625), to print out the filename and path? so just add 

```javascript
console.log(file);
```
After you find out which file is causing the error,  can you print the content of the file as well?

**Comment by skillzzjesse** [comment]
<img width="710" alt="screen shot 2016-12-05 at 08 56 01" src="https://cloud.githubusercontent.com/assets/15139826/20877397/bbfd68e0-bac8-11e6-91bb-c02a7437f697.png">

So I did as you asked and it seems like it's loading two files. The first file seems to be one of the hashed filenames created by the package itself, the second I'm not so sure.

Then it popped up into my head, I deleted the entire cache folder which seemed to do something. When I ran the program later It didn't seem to have any issues.

As you might have noticed from some of the previous screenshot I've send the entire folder is inside of a google drive client.... So I guess it's true what they say....google drive corrupts repositories..

The problem was probably the `Icon` file you see loaded on the second line, this is created by google drive, probably....

**Comment by akhoury** [comment]
Yup, Google Drive is adding `Icon`! ugh!

**Comment by skillzzjesse** [comment]
I don't know if anyone ever has this issue and if it's even worth it...but perhaps the program should check for the extension of the file. (given that `.json` will be added to the filename).
Or some other way to filter if the file was created by node-persist of course.

That would just be a cool feature that made the program a bit more robust, but as I said...It's not a key element and I doubt that errors like this happen a lot.

**Comment by akhoury** [comment]
> given that .json will be added to the filename 

Not really. We don't add `.json` notice the hashed valued in your cachedfolder. and for us to start adding `.json` means that backward compatibility will be broken.

One thing we can do is ignore the parsing error and just skip these files.

**Comment by skillzzjesse** [comment]
Backwards compatibility will indeed be broken, hadn't thought about that. (unless it's be an option, but that might just suck...)

> One thing we can do is ignore the parsing error and just skip these files.  

I agree that would be a better Idea, make sure to log the fact that you skipped over the files _(when logging is turned on)_ though. But that wouldn't be too much work I guess.

Do you want me to do a PR? (given that I can figure out a way to do this with )

**Comment by skillzzjesse** [comment]
It might also be a good idea to make skipping over these files and ignoring the error an optional thing. Perhaps something called `safemode` on the options (boolean value) would be smart?

**Comment by akhoury** [comment]
be my guest, try a PR

**Comment by skillzzjesse** [comment]
So I dived into the code, and read line after line trying to follow what's happening. 
It seems like `init` is reading the files etc. (quite obvious I know.)  So after the file is parsed it's pushed onto an array. I don't exactly know for what purposes (except the goal of the module of course) but that doesn't really matter. 

My question being, `self.parseFile()` returns `undefined` in case there's an error. This means that we need to skip over `undefined` files after parsing right?  Make sure they're not pushed onto the array.

**Comment by skillzzjesse** [comment]
Oeps no, that's wrong. There's also `self.parseFile` which is used in `parseStorageDir()`. So I guess we just skip over it from there. Or return undefined in case `self.parse()` is undefined.
