### ISSUE TITLE
Redis adapter

### ISSUE THREAD

**Issue by cigolpl** [simonlast/node-persist#74]
Hi, First of all great and very simple project to use. Have you ever considered Redis for this as the optional storage (instead of filesystem) ?

**Comment by akhoury** [comment]
I have thought about it, but adapting redis means that we can no longer support synchronous operations - not that I am in favor of synchronous operations at all, but this would mean breaking compatibility.

**Comment by cigolpl** [comment]
Yeah, in terms of synchronous operations that makes sense. Thanks!
