### ISSUE TITLE
TTL not working....

### ISSUE THREAD

**Issue by jessevdp** [simonlast/node-persist#79]
Heya, I'm having some issues with the TTL option of your module and was wondering if you could help me out.

I have a pretty basic setup of your module and basically have a function that checks if a value has been added to the storage yet. If this is the case it returns the key at which it's stored. If not it creates a new key and adds the value to the storage then returns the newly created key to the callback function.

For this functionality I use the `storage.forEach()` method. 

For testing purposes I set the TTL option in the `initSync()` function to `100`. According to your documentation this should set the TTL to 100 milliseconds. 

However when I run my testing function, a function that tries to add the same value to the storage every second, it returns the same KEY every single time. 

Then there's this quote from your docs that gets me even more confused:
>  With ttl (time to live), it is recommended that you use getItem(key, callback) or getItemSync(key) since, if a ttl of a certain key is expired the key-file is immediately deleted from disk, the callback will execute whenever that happends, if there is no ttl used or it has expired yet, the callback will also immediately execute in a synchronous fashion.

I really hope you'll be able to help me get the TTL working. Thanks in advance! 

## My code
Down here I'll share my source code, this might make it easier for you to see what's going on.

This is my module: 
```js
var KEY = require('my-key-generation')

module.exports = function (PATH, TTL) {
  /* Initialize the storage */
  storage.initSync({
    dir: PATH,
    ttl: TTL
  })

  /* Add existing KEYs to our KEY generator: This way it knows what keys to skip.
   * NOTE: this function is sync, but that's okey. It'll only be called on init. */
  KEY.list = storage.keys()

  return {
    getKey: function (ID, callback) {
      var returnval, exists

      /* First check if the id is already stored. */
      storage.forEach(function (key, value) {
        if (value === ID) {
          /* We've already stored this ID */
          exists = true
          returnval = callback(null, key)
        }
      })

      if (exists) {
        return returnval
      }

      /* We've looped over the entire storage but not found our ID, let's add it */
      var newKey = KEY()
      storage.setItem(newKey, ID, function (err) {
        if (err) {
          returnval = callback(err)
        }
        returnval = callback(null, newKey)
      })

      return returnval
    }
  }
}
```

And my testfile: 
```js
var module = require('./index.js')('./tokenstorage', 100)

module.empty(function (err) {
  if (err) throw err
  setInterval(function () {
    module.getKey('myfirstID', function (err, KEY) {
      if (err) throw err
      console.log('KEY: ' + KEY)
    })
  }, 1000)
})
```

**Comment by akhoury** [comment]
i dont understand why are you storing the `ID`s as values if they are unique? why not use the IDs as storage keys,

```
storage.setItemSync(ID, KEY); // store the KEY, or if you dont need the KEYs, just store anything, maybe storage.setItemSync(ID, 1); 

// then later somewhere in the code
storage.getItemSync(ID); // Then you will get a value, if that value is != null then you can use it.
```

**Comment by akhoury** [comment]
but anyways... your TTL is too little, you either need to make it more than the default [`expiredInterval`](https://github.com/simonlast/node-persist/blob/c250c4fa4808ab42ad28a079970358f66aed9926/src/local-storage.js#L21) which is 2 minutes by default, or change that to make it less than your TTL, so if you insist on a TTL of 100 milliseconds, then 
```javascript
 /* Initialize the storage */
  storage.initSync({
    dir: PATH,
    ttl: TTL, 
    expiredInterval: TTL < 2 * 60 * 1000 ? TTL/2 : 2 * 60 * 1000 
  // if TTL is less then 2 minutes, then run the interval every half of that, if not, leave it at 2 minutes
  })
```

**Comment by akhoury** [comment]
sorry, `expiredInterval` is new and we haven't added it to the documentation, will do.

**Comment by jessevdp** [comment]
> I don't understand why are you storing the IDs as values if they are unique? why not use the IDs as storage keys

For my current project I'm trying to figure out a way to make the authentication of my app as good as possible. The IDs being stored are actually database IDs of my users, the KEYs being stored will function as authentication keys/tokens for my users. 

The creation of KEYs is a randomised process to improve security. For example [JWT](https://jwt.io/) is a strategy where you take a database user and pull it trough an encryption, the authentication KEY will be the result of that encryption. When you then take the authentication key and pull it trough the decryption you get the database user. Which sucks..

By randomising the process of creating authentication keys your auth_keys are in no way related to the database. (besides the local storage module)

**Both KEY and ID are unique, but KEY is randomised!**

##

`expiredInterval` ohh, there's the catch. So I suppose by setting the TTL to true the records in the storage will be deleted **after** the `expiredInterval` has run out? Or how does this actually work? 

> If you insist on a TTL of 100 milliseconds.
I do not haha, not in production. This was merely to prove my point in my testing code. In the real world this is going to be more like a day or so.

**Comment by jessevdp** [comment]
I'm afraid I'm a bit confused about the whole mix of `expiredInterval` and `ttl`. Could you clear that up for me? If it's not too much trouble. ;)

**Comment by akhoury** [comment]
the `expiredInterval` basically means, how often should the "storage" instance run the [`removeExpiredItems`](https://github.com/simonlast/node-persist/blob/master/src/local-storage.js#L334) function to delete the expired keys, I set it by default to 2 minutes, but you can change it. see this block of code https://github.com/simonlast/node-persist/blob/master/src/local-storage.js#L675-L679

Granted, I could add a second check when `getItem` to make sure the value is not expired there as well.

**Comment by jessevdp** [comment]
Okey so basically if you set a `TTL` it's going to remove the expired `records` on an interval, which makes sense, even if the interval is 1ms it is still an interval, this can't be instant since it's a calculation of some sort. 

When working with the module it's quite confusing though, all these different options etc. Maybe it is really a good idea to check if something is expired whenever you run `getItem`, or at least check the specific `record` stored.

## Doesn't an interval make the actual TTL imprecise

Let's say you have your TTL configured to be 2 minutes, the same as the `expiredInterval`. Let's say you add a record to the storage exactly one minute after the last `expiredInterval` had run. A minute later the next `expiredInterval` runs and ignores this record, since its not expired yet. Another minute after that you expect the record to be deleted, the two minutes have run out. However when you `getItem` you are returned your value. The value you expected to be deleted. 

This is because the next expiredInterval will run a minute later and then delete this record.

In this scenario you would want the `getItem` function to check if your data is expired or not, since you EXPECTED the value to be deleted, yet it wasn't. 

This `expiredInterval` is useful though. Let's say you don't frequently access all the keys in your storage and the records only get deleted when checked. This would mean your storage fill would grow, since some keys just won't get deleted. This `expiredInterval` cronjob takes care of that part. 

## My conclusion
Also make sure keys are not expired when getting them and run the `expiredInterval` cron job as frequently as possible.

**Comment by akhoury** [comment]
added ttl to readme, closing....
