### ISSUE TITLE
error after hard reboot

### ISSUE THREAD

**Issue by jfix** [simonlast/node-persist#81]
I'm using `node-persist` on a raspberry pi where there is no on/off button to gracefully stop or reboot the machine. Therefore, I pull the usb (power) cable and plug it back in. This works for most applications, but I encounter the following problem in one of my apps:

I'm initializing the storage module synchronically like this:
```
storage.initSync({ttl: 8 * 60 * 60 * 1000})
```

Usually, after a hard reboot I get this stack trace in my log file:

```
TypeError: Cannot read property 'key' of undefined
    at LocalStorage.parseFileSync (/home/pi/lavazza/dash-button/node_modules/node-persist/src/local-storage.js:638:24)
    at LocalStorage.parseStorageDirSync (/home/pi/lavazza/dash-button/node_modules/node-persist/src/local-storage.js:602:26)
    at LocalStorage.initSync (/home/pi/lavazza/dash-button/node_modules/node-persist/src/local-storage.js:148:14)
    at Object.nodePersist.initSync (/home/pi/lavazza/dash-button/node_modules/node-persist/src/node-persist.js:37:32)
    at Object.<anonymous> (/home/pi/lavazza/dash-button/index.js:15:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Line 15 in file `index.js` corresponds to the `storage.initSync` I quoted above.

Deleting the `.node-persist` directory resolves the problem. So this is my workaround for the time being, but it would be cleaner if I wouldn't have to. Do you have an idea why this happens?

**Comment by akhoury** [comment]
i think i do, something is adding a non-parseable file in that directory, i think these 2 issues are related:
can you add a logging statement, as my instructions in this comment
https://github.com/simonlast/node-persist/issues/72#issuecomment-264754099

**Comment by akhoury** [comment]
also, can you turn on logging: 
```
storage.initSync({ttl: 8 * 60 * 60 * 1000, logging: true});
```

**Comment by akhoury** [comment]
upgrade to `node-persist@2.0.9` and try it again

```javascript
storage.initSync({ttl: 8 * 60 * 60 * 1000, logging: true});
```

You should see an error that points out the invalid file,

Then, use this option, `forgiveParseErrors` to ignore it.

```javascript
storage.initSync({ttl: 8 * 60 * 60 * 1000, forgiveParseErrors: true});
```

**Comment by jfix** [comment]
I'll try that later today. Thanks!

**Comment by jfix** [comment]
I upgraded to node-persist@2.0.10 and did some testing which seems to indicate that it's working when using the `forgiveParseErrors` option. Thanks a lot for your quick fix! So from my side you can close the issue.

**Comment by akhoury** [comment]
ok i will, but you might want to set `forgiveParseErrors: false` once to make it error and see which file is causing the parsing error, which would lead you to why is that file in there to begin with.

glad i could help

**Comment by jfix** [comment]
Yes, I will do that, you're right.
