### ISSUE TITLE
Setting max keys

### ISSUE THREAD

**Issue by Pascal66** [simonlast/node-persist#83]
Is there a way to set a max scale instead/with ttl ?
Could be a nice improvment ?

**Comment by akhoury** [comment]
like a maximum number of keys that it can hold? what's the use case? are you trying to limit RAM usage? if so, i would maybe go with `maxMegabytes` and we can calculate the size of each value being stored.

**Comment by Pascal66** [comment]
Yes for limiting ram usage, and forEach walking quicky with a limited number of key/values, and limiting the size of the json saved on file. So instead maxRam/sizeOfValue then just only maxValue for example, 64, 100, or anything little

**Comment by akhoury** [comment]
hmm.. we can also have a flag to NOT use RAM at all, or maybe for "frequently-accessed" keys, this way we store nothing (or a constant) in RAM and everything would be read from disk.

**Comment by akhoury** [comment]
version 3.0+ no longer stores everything in RAM, everything is on disk, and `forEach(callback)` now iterates each file at a time, not in parallel, we could have a parallel limit in the future if need be

note that in 3.0+ `forEach`'s `callback` takes an object as an argument, not 2 arguments

**Comment by akhoury** [comment]
https://github.com/simonlast/node-persist#300-change-logs
