### ISSUE TITLE
Is there a dispose function?

### ISSUE THREAD

**Issue by bmewburn** [simonlast/node-persist#84]
Thanks for creating this lib. I'm using it to cache a large number of items but wish to release these items from memory once I have read them. Can I dispose of the storage and re-init when needed?

**Comment by akhoury** [comment]
yea you can delete 1 item at a time using [`removeItem(key)`](https://github.com/simonlast/node-persist#removeitemkey-callback---asynchronous-returns-promise) or [`removeItemSync(key)`](https://github.com/simonlast/node-persist#removeitemsynckey---synchronous--throws-error-on-failure) 

or you can clear everything using [`clear()`](https://github.com/simonlast/node-persist#clearcallback---asynchronous-returns-promise) or [`clearSync()`](https://github.com/simonlast/node-persist#clearsync---synchronous-throws-error-on-failure)

**Comment by bmewburn** [comment]
I don't want to delete the cached items. I want to uninitialise.

**Comment by akhoury** [comment]
what do you mean by uninitialise? what are you trying to do? just release from memory but keep them on disk?
