### ISSUE TITLE
Does it lock?

### ISSUE THREAD

**Issue by salarelv** [simonlast/node-persist#85]
If I call setItem does it lock the given key for reading?
I have application where one process writes data into the database and another reads and removes when it has processed the data.

**Comment by akhoury** [comment]
nope, whichever comes first. the thing is it won't need to lock, it writes into RAM first, then persists to disk, maybe later, maybe soon after, so whatever is reading it, it's reading from RAM - think of it as a light version of redis db

**Comment by akhoury** [comment]
RAM comment is no longer valid, it all depends on the OS's disk I/O transactions
