### ISSUE TITLE
Migrating to latest version of node-persist (encrypted file names)

### ISSUE THREAD

**Issue by bbishwokarma** [simonlast/node-persist#87]
I used node-persist 0.0.11 during development of my application.  Current version is 2.0.11. Can anyone list the steps required to modify data to migrate to latest version, please? I see major changes such as encrypting file names, and including the key field inside the file itself too. Is there any tool that helps me migrate my data?

**Comment by akhoury** [comment]
unfortunately there are no tool to migrate the data, there are many changes. You could write a quick script to load 2 node-persist modules, one of 0.0.11 version and one of 2.0.11 version, then iterate over the data from 0.x then setItem() in the 2.x version.

but this is not as easy as it sounds, i recommend forking node-persist into a second local copy on your hard drive, then `git checkout d77462b81bc90d03a0d57140212b5a71c56aa7e7` which is the last commit hash of 0.0.11, then make sure you __rename it__ say to something else, so you can load them both at the same time, say something like "node-persist-legacy", i would rename the folder name and the package.json name.

```javascript
// load them both
var nodePersistLegacy = require("/path/to/your/node-persist-legacy");
var nodePersist = require("node-persist");

// init them both synchronously 
nodePersistLegacy.initSync({ 
   dir: "use/your/same/old/dir" 
    /* with whatever options you used to use */
});
nodePersist.initSync({ 
   dir: "/use/a/different/directory", 
   /* + whatever other new options */ 
});

// iterate over the old ones, save them in the new one 
nodePersistLegacy.forEach(function (key, value) {
   nodePersist.setItemSync(key, value);
});
```
i didn't test this, but you get the idea. Let me know if you need help.

**Comment by bbishwokarma** [comment]
Thank you Akhoury for the details. I will follow these steps and post the result in this thread.

**Comment by jvmahon** [comment]
I"m actually looking to do the same thing, but going from 0.0.11 version to the latest 3.0 version of persist. Were there any particular issues you encountered or guidance you have on doing this?  I.e., lessons learned, etc. Thanks.

**Comment by akhoury** [comment]
@jvmahon in 3.0, there are no more `*Sync` functions, so you just have to do every asynchronously 

say your filename is `migrate.js`

```javascript
// load them both
const nodePersistLegacy = require("/path/to/your/node-persist-legacy");
const nodePersist = require("node-persist");

// global async/await is not supported yet
(async () => {

  // init them both asynchronously, in parallel
   await Promise.all([
      nodePersistLegacy.init({ 
        dir: "use/your/same/old/dir" 
        /* with whatever options you used to use */
      }),

      nodePersist.init({ 
         dir: "/use/a/different/directory", 
         /* + whatever other new options */ 
      })
   ]); 

// iterate over the old ones, save them in the new one 

/*
  iterate that way
*/
nodePersistLegacy.forEach(async function (key, value) {
   await nodePersist.setItem(key, value);
});

/*
 OR iterate that way, slower, but probably better

let oldKeys = nodePersistLegacy.keys();
// depending on your node version, you might to use `node --harmony migrate.js` 
for await (let key of oldKeys) {
    let value = nodePersistLegacy.getItemSync(key);    
    await nodePersist.setItem(key, value);
}

*/

})();
```

## DISCLAIMER

I did __NOT__ test this block of code
