### ISSUE TITLE
Should an object retrieved with getItem be mutable?

### ISSUE THREAD

**Issue by tonyfleck76** [simonlast/node-persist#88]
I just came across this while using node-persist on a larger project, and managed to reproduce the issue I believe. It seems that when using getItem, the object that is returned is not a copy of the object that was stored, but the actual object itself. This means that if I get something from my storage, then modify something (Say, removing information I don't want to send to a client) I actually modify the object in the database. Here is an example.

```
const storage = require('node-persist');

async function persistTest () {
  let obj1 = { name: 'Bob', age: 20 }
  let obj2, obj3;

  console.log('Obj1 age: ' + obj1.age);

  console.log('Inserting Obj1');
  try {
    await storage.init({ dir: 'db' });
    await storage.setItem('obj1', obj1);
    console.log('Getting obj1 and storing in obj2');
    obj2 = await storage.getItem('obj1');
    console.log('Changing obj2 age');
    obj2.age = 21;
    console.log('Getting obj1 from database again');
    obj3 = await storage.getItem('obj1');
    console.log('Obj1 age: ' + obj1.age);
    console.log('Obj2 age: ' + obj2.age);
    console.log('Obj3 age: ' + obj3.age);
  } catch (err) {
    console.log(err);
  }
}

persistTest();
```

And the output from this example:

```
Obj1 age: 20
Inserting Obj1
Getting obj1 and storing in obj2
Changing obj2 age
Getting obj1 from database again
Obj1 age: 21
Obj2 age: 21
Obj3 age: 21
```

Surely this isn't intended behavior? It seems that by modifying the obj2, I should not change obj1. And, I definitely shouldn't be changing anything in storage so that when I call getItem again for obj3 it also shows age as 21. Perhaps this has something to do with how caching works? Is there a way to fix this?

**Comment by akhoury** [comment]
yea, you're right, we should "stringify" for storage in memory as well. will fix
