### ISSUE TITLE
performance problem

### ISSUE THREAD

**Issue by ramarro123** [simonlast/node-persist#90]
Hi,

i noticed a performance problem (caused by very very low performance hardware)

> [db] [17-06-26 10:26:40] INFO: benckmark setItem took 479110395
> [db] [17-06-26 10:27:43] INFO: benckmark setItem took 148815

note the code above, setitem took x100 times before and after the fix.
i see that on setitem you do 

> 
> var logmsg = "set (" + key + ": " + this.stringify(value) + ")";

even if log function it's disabled/false.
this.stringify(value) it's overkilling in my scenario, i have to run a nodejs in an armv5 crappy devices, and the value is a 20000 obj array updated every second (data comes from an IOT devices via mqtt, nodejs need to unshift the array, validate, add data to statistics and store them in memory -later persist them-)

can i suggest to take it out the stringify or at least execute it only if someone want to log it?

**Comment by akhoury** [comment]
relevant https://github.com/simonlast/node-persist/commit/5a52fb882380ec7bfe8171b2490ea50a45dc8fb8
