### ISSUE TITLE
getItem raw

### ISSUE THREAD

**Issue by ramarro123** [simonlast/node-persist#91]
Hi,

since the objects are "stryingified" and saved into a json on disk, it's possible to getitemRaw as a string instead of object?

in my case stringify it's a big overhead due to low power system, and if the object it's already in memory it will save me to do getItem->stringify to serve it via web page.

of course stringify version should be updated when object get serialized to disk, it's find to have an old version (at least in my case) or a promise that get called when the object get stored to disk.

**Comment by akhoury** [comment]
version 3.0+ now has `getRawDatum()`
```javascript
await storage.setItem('mykey', 'myvalue');

let stringifiedDatum = await storage.getRawDatum('mykey');
// "{"key": "mykey", "value": "myvalue"}"
```
