### ISSUE TITLE
Manual Reset would be great

### ISSUE THREAD

**Issue by djjayballz** [simonlast/node-persist#98]
Hi,
I'm using your wonderful persist-node for storing graph data. While I'm troubleshooting my flows I'm filling up my graphs with data. It would be great if a simple "msg.reset"-injection would wipe the stored.data.

Now I remove the .json-file

best regards

**Comment by akhoury** [comment]
have you tried `storage.clear()` or `storage.clearSync()` ?

**Comment by akhoury** [comment]
version 3.0 no longer stores data in RAM, but if you want to delete all stored keys use:

```javascript
await storage.clear();
```
