### ISSUE TITLE
corrupt file after deleting item from persisted array

### ISSUE THREAD

**Issue by dtemes** [simonlast/node-persist#99]
Removing items from a persisted array will result in unproperly formatted data in the stored file. It looks like file is not purged before writing.

```
var messages = ["A","B","C"];
storage.setItem("messages", messages);
...
messages = ["A","B"];
storage.setItem("messages", messages);
```

file contens after the second setItem:
`{"key":"messages","value":["A","B"]}C"]}`

Running node v8.9.4 on windows with node-persist 2.1.0

**Comment by akhoury** [comment]
does it happen if you use `setItemSync` instead of `setItem`?

**Comment by dtemes** [comment]
No, it does not happen with the sync version.

As a workaround I am doing a del before writing the updated key.

**Comment by akhoury** [comment]
well, your code is using async functions as sync, i could probably add a queue to prevent that but still, you should be using async code when calling async functions.

```javascript
// if this code is executing inside a function, make it it async, if it's global do this
(async () => {
  var messages = ["A","B","C"];
  await storage.setItem("messages", messages);
/// ...
  messages = ["A","B"];
  await storage.setItem("messages", messages);
})();
```

Or using promises

```javascript
 var messages = ["A","B","C"];
 storage.setItem("messages", messages)
    .then(() => {
       messages = ["A","B"];
       return storage.setItem("messages", messages);
    });
```

**Comment by dtemes** [comment]
What would happen if the key is updated from other not related async methods as for instance from http requests?

I understand that this is related to the way fs.writefile works, so as you suggest i will use the sync methods instead. 

From the File SYstem documentation:

"Note that it is unsafe to use fs.writeFile multiple times on the same file without waiting for the callback. For this scenario, fs.createWriteStream is strongly recommended."

**Comment by akhoury** [comment]
@dtemes this module is not designed to be used as a database that accepts requests from multiple http requests, this is a simple utility to store data for things like a script or something that runs independently.

if you're building a web server, you should use a proper database server, like mysql, mongo, redis etc..

**Comment by akhoury** [comment]
anyways, i'm closing this issue because it sounds like you have a concurrency issue here, which is a duplicate issue we talk about here= https://github.com/simonlast/node-persist/issues/31
